import { useState } from "react";
import { useLifeStore } from "../../app/store";
import { PageIntro } from "../../components/dashboard/PageIntro";
import { SectionCard } from "../../components/SectionCard";
import { askLifeAgent } from "../../services/aiService";

export function PlannerPage() {
  const state = useLifeStore();
  const addTask = useLifeStore((s) => s.addTask);
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState([]);

  const generatePlan = async () => {
    setLoading(true);
    try {
      const prompt = "Based on goals and learning items, generate 5 concrete tasks for this week. Return plain bullet lines only.";
      const data = await askLifeAgent({
        message: prompt,
        context: { goals: state.goals, learningItems: state.learning, tasks: state.tasks, habits: state.habits }
      });
      const lines = (data.reply || "").split("\n").map((x) => x.replace(/^[-*\d.\s]+/, "").trim()).filter(Boolean).slice(0, 7);
      setPlan(lines.length ? lines : ["Plan one high-priority goal task", "Plan one deep-learning session", "Plan one review task"]);
    } finally {
      setLoading(false);
    }
  };

  const pushAllToTasks = () => {
    plan.forEach((title) => {
      addTask({ title, priority: "High", status: "Pending", deadline: "", goalId: "", category: "AI Planned", notes: "Generated by AI Auto-Planner" });
    });
    setPlan([]);
  };

  return (
    <div>
      <PageIntro title="AI Auto Planner" subtitle="Convert goals into an execution-ready weekly task list." chips={["Goal-driven", "AI generated", "One-click to tasks"]} />
      <div className="grid xl:grid-cols-2 gap-4">
        <SectionCard title="Generate Weekly Plan" subtitle="Uses your goals + learning context">
          <button className="rounded-lg px-4 py-2 bg-[var(--accent)] text-black font-semibold" onClick={generatePlan}>{loading ? "Generating..." : "Generate Plan"}</button>
        </SectionCard>

        <SectionCard title="Planned Tasks" subtitle="Review and push into your task board">
          <div className="space-y-2 mb-3">
            {plan.map((p, i) => <div key={i} className="rounded-lg border border-[var(--panel-border)] bg-black/20 p-2 text-sm text-slate-200">{p}</div>)}
            {!plan.length ? <p className="text-sm text-slate-500">No generated plan yet.</p> : null}
          </div>
          <button disabled={!plan.length} className="rounded-lg px-4 py-2 border border-[var(--accent-soft)] text-[var(--accent-text)] disabled:opacity-50" onClick={pushAllToTasks}>Add All To Tasks</button>
        </SectionCard>
      </div>
    </div>
  );
}
